stages:
  - test
variables:
  DEBIAN_FRONTEND: noninteractive
  PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin"

test:
  stage: test
  image: debian:sid
  environment:
  script:
    - apt-get update
    - apt-get install -y eatmydata
    - eatmydata apt install -y
      build-essential
      curl
      sudo
      libapt-pkg-dev
      codespell
    - curl https://sh.rustup.rs -sSf | sh -- /dev/stdin -y
    - cargo install just
    - just setup-dev
    - just check
