[package]
name = "nala-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-apt = { git = "https://gitlab.com/volian/rust-apt" }
clap = { version = "3.2.13", features = ["derive"] }
lazy_static = "1.4.0"
toml = "0.5"
anyhow = "1.0.59"

[build-dependencies]
clap = { version = "3.2.13", features = ["derive"] }
clap_complete = "*"

[profile.release-lto]
inherits = "release"
lto = true
