[package]
name = "nala-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-apt = { git = "https://gitlab.com/volian/rust-apt" }
# rust-apt = { path = "../rust-apt" }
# rust-apt = "*"
clap = { version = "3.2", features = ["derive"] }
lazy_static = "1.4"
once_cell = "1.13"
toml = "0.5"
anyhow = "1.0"
regex = "1.6"
glob = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
clap = { version = "3.2", features = ["derive"] }
clap_complete = "*"

[profile.release-lto]
inherits = "release"
lto = true
